
CREATE TABLE Countries
(
Id INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Customers
(
Id INT IDENTITY PRIMARY KEY,
FirstName NVARCHAR(25) NOT NULL,
LastName NVARCHAR(25) NOT NULL,
Gender CHAR(1)
CHECK(Gender IN('M','F')) ,
Age INT NOT NULL,
PhoneNumber VARCHAR(10)
CHECK(LEN(PhoneNumber)=10),
CountryId INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL

)

CREATE TABLE Products
(
Id INT IDENTITY PRIMARY KEY,
Name NVARCHAR(25) UNIQUE NOT NULL,
[Description] NVARCHAR(250)  NOT NULL,
Recipe NVARCHAR(MAX) NOT NULL,
Price DECIMAL(18,2) CHECK(Price>=0) NOT NULL
)

CREATE TABLE Feedbacks
(
Id INT IDENTITY PRIMARY KEY,
[Description] NVARCHAR(255) ,
Rate DECIMAL(18,2) 
CHECK(Rate BETWEEN 0 AND 10),
ProductId INT FOREIGN KEY REFERENCES Products(Id) NOT NULL,
CustomerId INT FOREIGN KEY REFERENCES Customers(Id) NOT NULL
)

CREATE TABLE Distributors
(
Id INT IDENTITY PRIMARY KEY,
Name NVARCHAR(25) UNIQUE NOT NULL,
AddressText NVARCHAR(30) UNIQUE NOT NULL,
Summary NVARCHAR(200) NOT NULL,
CountryId INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL,

)

CREATE TABLE Ingredients
(
Id INT IDENTITY PRIMARY KEY,
Name NVARCHAR(30)  NOT NULL,
[Description] NVARCHAR(200)  NOT NULL,
OriginCountryId INT FOREIGN KEY REFERENCES Countries(Id) NOT NULL,
DistributorId INT FOREIGN KEY REFERENCES Distributors(Id) NOT NULL
)

CREATE TABLE ProductsIngredients
(
ProductId INT FOREIGN KEY REFERENCES Products (Id),
IngredientId INT FOREIGN KEY REFERENCES Ingredients (Id),
PRIMARY KEY(ProductId,IngredientId)

)