CREATE TABLE Clients
(
ClientId INT IDENTITY PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone CHAR(12) 
CHECK(LEN(Phone)=12),

)

CREATE TABLE Mechanics
(
MechanicId INT IDENTITY PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Address VARCHAR(255) NOT NULL,
)

CREATE TABLE Models
(
ModelId INT IDENTITY PRIMARY KEY ,
Name VARCHAR(50) UNIQUE NOT NULL
)


CREATE TABLE Jobs
(
JobId INT IDENTITY PRIMARY KEY ,
ModelId INT FOREIGN KEY REFERENCES Models(ModelId) NOT NULL,
[Status] VARCHAR(11) DEFAULT 'Pending'
CHECK(Status IN ('Pending','In Progress','Finished')),
ClientId INT FOREIGN KEY REFERENCES Clients(ClientId) NOT NULL,
MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId) ,
IssueDate DATE NOT NULL,
FinishDate DATE 
)

CREATE TABLE Orders
(
OrderId INT IDENTITY PRIMARY KEY,
JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
IssueDate DATE ,
Delivered BIT DEFAULT(0) NOT NULL
)

CREATE TABLE Vendors
(
VendorId INT IDENTITY PRIMARY KEY,
Name VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Parts
(
PartId INT IDENTITY PRIMARY KEY,
SerialNumber VARCHAR(50) UNIQUE NOT NULL,
Description VARCHAR(255),
Price DECIMAL(18,2) 
CHECK(Price > 0),
VendorId INT FOREIGN KEY REFERENCES Vendors(VendorId) NOT NULL,
StockQty INT DEFAULT 0
CHECK(StockQty >= 0)

)

CREATE TABLE OrderParts
(
OrderId INT FOREIGN KEY REFERENCES Orders(OrderId),
PartId INT FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT DEFAULT 1
CHECK(Quantity > 0),
CONSTRAINT PK_OrderParts PRIMARY KEY(OrderId,PartId)
)

CREATE TABLE PartsNeeded
(
JobId INT FOREIGN KEY REFERENCES Jobs(JobId),
PartId INT FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT DEFAULT 1
CHECK(Quantity > 0),
CONSTRAINT PK_PartsNeeded PRIMARY KEY(JobId,PartId)
)